# Generated by Django 4.2.3 on 2024-05-04 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="profile",
            name="github",
            field=models.URLField(
                validators=[django.core.validators.URLValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="linkedin",
            field=models.URLField(
                validators=[django.core.validators.URLValidator()]
            ),
        ),
    ]
